export const icdxList = [
  {icdx: 'A00', penyakit: 'Kolera'},
  {icdx: 'A09', penyakit: 'Diare'},
  {icdx: 'A06', penyakit: 'Diare Berdarah'},
  {icdx: 'A01', penyakit: 'Tifus perut klinis'},
  {icdx: 'A15', penyakit: 'TBC Paru TBA (+)'},
  {icdx: 'A16', penyakit: 'Tersangka TB Paru'},
  {icdx: 'A30', penyakit: 'Kusta PB'},
  {icdx: 'A30', penyakit: 'Kusta MB'},
  {icdx: 'B05', penyakit: 'Campak'},
  {icdx: 'A36', penyakit: 'Difteri'},
  {icdx: 'A37', penyakit: 'Batuk Rejan'},
  {icdx: 'A35', penyakit: 'Tetanus'},
  {icdx: 'B15', penyakit: 'Hepatitis Klinis'},
  {icdx: 'B54', penyakit: 'Malaria Klinis'},
  {icdx: 'B51', penyakit: 'Malaria Vivax'},
  {icdx: 'B50', penyakit: 'Malaria Falsifarum'},
  {icdx: 'B52', penyakit: 'Malaria Mix'},
  {icdx: 'A91', penyakit: 'Demam Berdarah Dengue'},
  {icdx: 'A90', penyakit: 'Demam Dengue'},
  {icdx: 'J13', penyakit: 'Pneumonia'},
  {icdx: 'A50', penyakit: 'Sifilis'},
  {icdx: 'A54', penyakit: 'Gonorrhoe'},
  {icdx: 'A66', penyakit: 'Frambusia'},
  {icdx: 'B74', penyakit: 'Filariasis'},
  {icdx: 'J10', penyakit: 'Influensa'},
  {icdx: 'J45', penyakit: 'Asthma'},
  {icdx: 'K29', penyakit: 'Gastritis'},
  {icdx: 'J47', penyakit: 'Bronchitis'},
  {icdx: '140', penyakit: 'Jantung'},
  {icdx: '110', penyakit: 'Hipertensi'},
  {icdx: 'D00-D09', penyakit: 'Kanker'},
  {icdx: 'E10-E14', penyakit: 'Diabetes Mellitus'},
  {icdx: 'Q60', penyakit: 'Ginjal'},
  {icdx: 'B18', penyakit: 'Radang Hati Menahun'},
  {icdx: 'B16', penyakit: 'Radang Hati Menular'},
  {icdx: 'P10-P15', penyakit: 'Trauma Lahir'},
  {icdx: '042', penyakit: 'Prematur'},
  {icdx: 'O03', penyakit: 'Spontan Aborsi'},
  {icdx: 'O04', penyakit: 'Medical Aborsi'},
  {icdx: 'O05', penyakit: 'Aborsi Lain Lain'},
  {icdx: 'I64', penyakit: 'Stroke'},
  {icdx: '-', penyakit: 'Lain-lain'}
];